apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node
      - job_name: 'kubernetes-services'
        kubernetes_sd_configs:
          - role: service
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod

